util-linux: build setpriv requires libcap-ng
There might a failure when build util-linux with the meta-selinux layer:

[snip]
sys-utils/setpriv.c:21:20: fatal error: cap-ng.h: No such file or directory
 #include <cap-ng.h>
                    ^
compilation terminated.
[snip]

Use PACKAGECONFIG to fix the problem.

[YOCTO #6026]

(From OE-Core rev: 8a6b1ae336a41292ee314c04d93c2c355c772762)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 1f85f07414e96aee2603ce61100008dbe7169973