gcc-configure-target: Add --enable-dependency-tracking to EXTRA_OECONF
Fixes errors seen while compiling gcc 4.8 for target, errors like

| /home/khem/work/angstrom/build/tmp-angstrom_next-eglibc/work-shared/gcc-4.8.0-r0/gcc-4.8.0/libatomic/cas_n.c:125:1: fatal error: opening dependency file .deps/cas_1_.lo.Ppo: No such file or directory

which are due to disabled dependency tracking but dependency files being still generated
while compiling libatomics.

(From OE-Core rev: c83cbc80af078d7be5deec44bba6e0ca29a5ee1a)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Saul Wold <sgw@linux.intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 1e7b9ef7e2b46b23572e96194fd1deaec5bebb26