qt4-embedded: support c++0x stand for directfb
While directfd upgrade to 1.7.6, it always includes directfb++ utils
when C++ is used and set c++0x as c++ standard.
(In git://git.directfb.org/git/directfb/core/DirectFB.git
commit b444bcae3197be9faf883460dcc239ef757d5922, and commit
522beeb76f2a8d2dee30d928d2a5955bd06cf25c)

The directfd in qt4-embedded is c++, and there was a build failure:
...
| qdirectfbwindowsurface.cpp:336:69: error: in C++98 'rect' must be
initialized by constructor, not by '{...}'
|      const DFBRectangle rect = { r.x(), r.y(), r.width(), r.height() };
...

The g++ used c++98 as default c++ standard, we should
explicitly set c++0x for directfd in qt4-embedded.

(From OE-Core rev: 833cb0e47f7542a67bdf943cede1754b7a20c1d9)

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 5b7371b832f594aaeb3564fd4a64d8583e337b67