libxml2: added python dependency to nativesdk
This is necessary since libxml2 has python dependency.

This patch will fix this error:
...
/path/to/build/system/4.7.2/ld: cannot find -lpython2.7
...
ERROR: Task 4152 (virtual:nativesdk:meta/recipes-core/libxml/libxml2_2.9.0.bb, do_compile) failed with exit code '1'

(From OE-Core rev: 4f2b3e3831bdc5707eacdab571ab207d8b09953e)

Signed-off-by: Felipe F. Tonello <eu@felipetonello.com>
Signed-off-by: Saul Wold <sgw@linux.intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 407bce925b496808224e50ca37286f3937129042