linux-dummy: catch up with image.bbclass changes
image.bbclass now depends on virtual/kernel:do_deploy, so add a task for that.

This fixes errors like this:

	ERROR: Task do_build in /build/linaro/build/meta-linaro/meta-linaro/recipes-linaro/images/linaro-image-lng.bb depends upon non-existent task do_deploy in /build/linaro/build/openembedded-core/meta/recipes-kernel/linux/linux-dummy.bb

(From OE-Core rev: 26d07f2a5bef42a113c9c81f2b5701b4f3d10d47)

Signed-off-by: Koen Kooi <koen.kooi@linaro.org>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: baf77657191bd64d715af425e0aaa2223d641863