screen: backport to fix build error
It fails to compile screen rarely with:

|.../4.3.1-r0/screen-4.3.1/display.h:154:19: error: 'T_N' undeclared here (not in a function)
|   union tcu d_tcs[T_N]; /* terminal capabilities */
|                      ^

Macro T_N is defined in header file term.h but it may not be created
then fails. Backport patch to make sure term.h is created before compile
other source codes.

(From OE-Core rev: 81499ff3bd60dfa931fbae75922a342c31251480)

Signed-off-by: Kai Kang <kai.kang@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: e384b970adcf0a742240fbbdf5b2b81b938ed0a9