wpa-supplicant: Add dependency on openssl
Building of wpa-supplicant failed due to missing dependency on openssl:
crypto_openssl.c:10:30: fatal error: openssl/opensslv.h: No such file or directory

(From OE-Core rev: 9d1cdb59cb9fcbc4927f04a226405766ab3c4fc8)

Signed-off-by: Mikhail Durnev <Mikhail_Durnev@mentor.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 58df7bb853035620b2aca494b5bcbc64ce8f5b80