qt4.inc: depend on tiff
* Fixes the following error with qt4-embedded-4.8.0 and possibly others:

| ../../../gui/image/qtiffhandler.cpp:48:20: fatal error: tiffio.h: No such file or directory

(From OE-Core rev: d0853052228128ccca2b744dae9c4dceae23067a)

Signed-off-by: Andreas Oberritter <obi@opendreambox.org>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 13949f2100d179ead5136fa9d636c09588d4b0b4