grub-efi-native_2.00.bb: fix a build issue
Due to recent change in the oecore layer grub-efi recipe uses separate
builddir and the paths used in the do_deply need to change accordingly.

This change avoids this build issue:
install: cannot stat `/build-fri2/tmp/work/x86_64-linux/grub-efi-i586-native/2.00-r1/grub-2.00/bootia32.efi': No such file or directory
ERROR: Function failed: do_deploy (see /build-fri2/tmp/work/x86_64-linux/grub-efi-i586-native/2.00-r1/temp/log.do_deploy.5875 for further information)

(From OE-Core rev: 11ba0231244b8a27939969353e3aa668ce78f7c6)

Signed-off-by: Nitin A Kamble <nitin.a.kamble@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 21288ac9da291c73fec4601013128158f5da0897