systemtap: Systemtap can not be build w -O0 optimization
Systemtap will fail with:

../usr/include/features.h:330:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
|  #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)

Use the same technique that eglibc uses to catch and correct the optimization
level, changing to -O2.

(From OE-Core rev: 9ceebb966e5294a270222475ab6317dcae2952fa)

Signed-off-by: Mark Hatle <mark.hatle@windriver.com>
Signed-off-by: Saul Wold <sgw@linux.intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 65385d4bb92c8938a48281462448d1efc6123920