ltp: Don't link against libfl
We have already defined yywrap function in scan.l file. After this, we no
longer need to link against libfl.
Since we are using --as-needed by default in linker, which means we end
up with errors like

	libfl.so: undefined reference to `yylex'

(From OE-Core rev: db8b59b4ffee73c6e80029083793531d7fd408c4)

Signed-off-by: Chong Lu <Chong.Lu@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: a511b2554d09298cae1381b454b9d00981ca8692