lsbinitiscripts: Add glib-2.0 to DEPENDS list
ppp-watch requires it.

x86_64-poky-linux-gcc    -m64 --sysroot=/intel/poky2/builds/fetch/tmp/sysroots/qemux86-64 -O2 -pipe -g -feliminate-unused-debug-types  -Wall -D_GNU_SOURCE `pkg-config glib-2.0 --cflags` -c ppp-watch.c -o ppp-watch.o
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
ppp-watch.c:78:18: fatal error: glib.h: No such file or directory
compilation terminated.
make[1]: *** [ppp-watch.o] Error 1
make[1]: Leaving directory `/intel/poky2/builds/fetch/tmp/work/x86_64-poky-linux/lsbinitscripts-9.03-r0/initscripts-9.03/src'

(From OE-Core rev: 488610f4a5b7591a989ff1a6137f276a85fd7a85)

Signed-off-by: Saul Wold <sgw@linux.intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: d83e034b4af747769c2ece26072c44f82bfbc11f