nspr 4.8.9: failed to build on x86_64 board
nspr failed to build on x86_64 board(e.g., qemux86-64):

x86_64-poky-linux-gcc    -m64 ... -m32 ...
...
fatal error: gnu/stubs-32.h: No such file or directory

This is because there are both '-m64' and '-m32' in gcc's options, and
the later one is used, but what we need is '-m64' since it is x86_64,
this is caused by an incorrect logic in configure.in, we should assume
that the pkg uses 64bit when target_cpu is x86_64 (it has two options:
--enable-n32 and --enable-64bit, both of them are not set by default),
we only can assume that the pkg uses 32bit when USE_N32 is set. But
what it did was that assumed 32bit when target_cpu was x86_64 unless
--enable-64bit was set, this seems unreasonable and caused the "gcc -m64
-m32" error.

Some had noticed this error before:
https://lists.yoctoproject.org/pipermail/poky/2011-May/005799.html

NOTE:
* Both fix configure and configure.in since we can't run the
  "autoreconf" for nsrp, please see more explanation in
  trickly-fix-build-on-x86_64.patch.

* Also fixed powerpc64, this is just fixed by conclusion since we don't
  suport ppc64.

[YOCTO #2179]

(From OE-Core rev: 1d8fea3b9c9dd8f3e2b72ee8c8a9b834f4a3d729)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 7b01671f54f70c28c98457058c51ffefcb07c0e8