Revert "blktrace: fix and enable parallel build"
This reverts commit 7050879f01b578511253304f0de9ecace355bdbf [formerly 2d9763a1c8685e9bd3a6b0aa0995eec5112dc4a7].

There are a few parallel issues:
1)
../rbtree.o: error adding symbols: Invalid operation
collect2: error: ld returned 1 exit status
Makefile:42: recipe for target 'btt' failed

2)
git/blkiomon.c:216: undefined reference to `rb_insert_color'
collect2: error: ld returned 1 exit status
Makefile:27: recipe for target 'blkparse' failed

3)
ld: rbtree.o: invalid string offset 128 >= 125 for section `.strtab'

4)
btreplay.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status

btreplay/btreplay.c:47:18: fatal error: list.h: No such file or directory

(From OE-Core rev: 35bb619486d7f5721e8fa86c8744d4cea4d1746a)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: e67611baa582aa5aef342bc678b4e43c13ff3323