perl-rdepends: be more strict in multiline comment
* fails to parse when http://patchwork.openembedded.org/patch/40997/ is used
Parsing recipes...ERROR: There is a confusing multiline, partially commented expression on line 10 of file
/OE/shr-core/openembedded-core/meta/recipes-devtools/perl/perl-rdepends_5.14.2.inc (| sed "s/\/.*\.pm: */ += /g;s/[\"\']//g;s/;.*/\"/g;s/+=
.*\(require\|use\)\> */+= \"perl-module-/g;s/CPANPLUS::.*/cpanplus/g;s/CPAN::.*/cpan/g;s/::/-/g;s/
[^+\"].*//g;s/_/-/g;s/\.pl\"$/\"/;s/\"\?\$/\"/;s/(//;" | tr [:upper:] [:lower:] \).
Please clarify whether this is all a comment or should be parsed.
ERROR: Unable to parse /OE/shr-core/openembedded-core/meta/recipes-devtools/perl/perl_5.14.2.bb: Exited with "1"
ERROR: Command execution failed: Exited with 1

(From OE-Core rev: daee2d2dc29c14a086122c04fbf97924c5dab3b8)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 54b8096f91af47c72ac9abffe2f5c73fee27ad57