cmake-native: disable check for acl.h
We build cmake-native without acl support. However, the acl.h header
is still being checked which would sometimes cause the following error
during do_compile:

     archive_read_disk_entry_from_file.c:38:21: fatal error: sys/acl.h: No such file or directory
     |  #include <sys/acl.h>
     |                      ^
     | compilation terminated.

This happens when the sysroot parts of acl-native is removed between
do_configure and do_compile tasks of cmake-native.

To reproduce the problem manually, execute the following command:

bitbake cmake-native -c cleansstate && bitbake acl-native -c cleansstate && \
bitbake	acl-native && bitbake cmake-native -c configure	&& \
bitbake acl-native -c cleansstate && bitbake cmake-native -c compile

This patch fixes the above problem by explicitly disable the checking for
acl.h header file.

(From OE-Core rev: 3ad1701b0afe59af9d8427d53ffa4c0f52f42805)

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 02f010b99f86a74aa5ccbff431da1d6181c50bda