machine/qemu: Fix OpenGL/GLX support with xserver-xorg.
  * The Xorg server needs to load the GLX extension in order to
    enable proper OpenGL support.

  * Before this patch, glxinfo aborted with:

      root@qemux86:~# glxinfo
      name of display: :0.0
      Error: couldn't find RGB GLX visual or fbconfig

  * After this patch, it works as expected:

      root@qemux86:~# glxinfo | grep " render"
      direct rendering: Yes
      OpenGL renderer string: Software Rasterizer

(From OE-Core rev: 8f33627684755899c5b1fd7eeefdd89c42e68fec)

Signed-off-by: Carlos Alberto Lopez Perez <clopez@igalia.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 67959b9a15bc775158197926c3a0bcb557149777