udev: fix /var/volatile/tmp permissions
Mariadb postinstall will fail with:

ERROR: 1  Can't create/write to file '/tmp/#sql_a2a_0.MAI' (Errcode: 13)
140814  8:14:06 [ERROR] Aborting

/tmp is a link to /var/volatile/tmp, set as:

drwxr-xr-x 3 root root 60 Aug 14 08:07 .

populate-volatiles.sh does not create the directory or set
permissions, because it already exists:

Checking for -/var/volatile/tmp-.
Creating directory -/var/volatile/tmp-.
Target already exists. Skipping.

Traced the creation to the initfile in udev. Create with -m 1755
to be sure. With this patch applied, mysql postinst succeeds and
creates the neccesary user tables.

(From OE-Core rev: 5743c7632ac9c33051f6fca60f5507d3808e8e3a)

Signed-off-by: Riku Voipio <riku.voipio@linaro.org>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: bf6ad8202caaac6285ca0eb7089c0d92eca63527