powerpc e500: set -mfloat-gprs=double
Use of FPRs instead of GPRs is incompatible with e500/SPE, so let's be
explicit about the use of GPRs to avoid potential errors. For example, with
the Sourcery G++ toolchain, one can hit: conftest.c:1:0: error: E500 and FPRs
not supported.

(From OE-Core rev: 32bb6afe3e6f3e374e4d14edc238b46a90d44169)

Signed-off-by: Christopher Larson <chris_larson@mentor.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: f1f7680263143a67ca345970ab8d3f91d14934a5