lttng-tools: fixes a wrong header issue
This fixes a following compiling issue:
| agent.c:33:19: fatal error: error.h: No such file or directory
|  #include "error.h"

it's back-ported from lttng-tools upstream, we need it in SRC_URI
since 2.8 is still the latest release.

(From OE-Core rev: 08c9a363cc600cb58ab98cf22de0f7963720dea3)

Signed-off-by: Ming Liu <peter.x.liu@external.atlascopco.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: a9f4b94f4fe4d4c626f3c7cd57582ca4e5b57e8d