python: adding missing runtime dependency python-io to python-pprint
When trying to import python-pprint on a minimal image, it reports that
the cStringIO python module is missing.
This is provided with python-io, so we add python-io as runtime
dependency.

The complete observed trace was:

Python 2.7.3 (default, Apr  4 2013, 07:45:36)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pprint
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/pprint.py", line 40, in <module>
    from cStringIO import StringIO as _StringIO
ImportError: No module named cStringIO

(From OE-Core rev: abe7bf9992e298f1b53e790eee7b064a9e4e8589)

Signed-off-by: Lukas Bulwahn <lukas.bulwahn@oss.bmw-carit.de>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 88f446661b7b211045d42f012f49630cb19f0842