eglibc: Add patch to fix /var installation location
This address the packaging issues since it's installed in the wrong place
ERROR: For recipe eglibc-nativesdk, the following files/directories were installed but not shipped in any package:
ERROR:   /var
ERROR:   /var/db
ERROR:   /var/db/Makefile

(From OE-Core rev: 22a2297c712d3b3ca0335197943483218c92ef3e)

Signed-off-by: Saul Wold <sgw@linux.intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 2e1974d774a0e1850cbf3e7a8a2f39729ad1b816