core-image-{minimal, testmaster}-initramfs: set COMPATIBLE_HOST
* use the same COMPATIBLE_HOST restriction as initramfs-live-install(-testfs)
  to resolve ugly error when trying to build them e.g. for ARM:

  ERROR: Nothing RPROVIDES 'initramfs-live-install-testfs' (but /home/jenkins/oe/world/shr-core/openembedded-core/meta/recipes-extended/images/core-image-testmaster-initramfs.bb RDEPENDS on or otherwise requires it)
  ERROR: initramfs-live-install-testfs was skipped: incompatible with host arm-oe-linux-gnueabi (not in COMPATIBLE_HOST)
  NOTE: Runtime target 'initramfs-live-install-testfs' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['initramfs-live-install-testfs']
  ERROR: Required build target 'core-image-testmaster-initramfs' has no buildable providers.
  Missing or unbuildable dependency chain was: ['core-image-testmaster-initramfs', 'initramfs-live-install-testfs']

  ERROR: Nothing RPROVIDES 'initramfs-live-install' (but /home/jenkins/oe/world/shr-core/openembedded-core/meta/recipes-core/images/core-image-minimal-initramfs.bb RDEPENDS on or otherwise requires it)
  ERROR: initramfs-live-install was skipped: incompatible with host arm-oe-linux-gnueabi (not in COMPATIBLE_HOST)
  NOTE: Runtime target 'initramfs-live-install' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['initramfs-live-install']
  ERROR: Required build target 'core-image-minimal-initramfs' has no buildable providers.
  Missing or unbuildable dependency chain was: ['core-image-minimal-initramfs', 'initramfs-live-install']

(From OE-Core rev: 8016b51d81ca9ed1567effa9d2870b1d98684350)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: aac36591db785922aba262e6c5b5fca11a115d4c