matchbox-desktop: remove 0.9.1 and 2.0 version
For 0.9.1:
ERROR: matchbox-wm: Recipe file does not have license file information (LIC_FILES_CHKSUM)
ERROR: Licensing Error: LIC_FILES_CHKSUM does not match, please fix

For 2.0:
| /path/to/matchbox-desktop-2.0/configure: line 2488: syntax error near unexpected token `build_old_libs,'
| /path/to/matchbox-desktop-2.0/configure: line 2488: `    _LT_DECL(build_old_libs, enable_static, 0,'

And there is a matchbox-desktop_git.bb which is "GPLv2+ & LGPLv2+", so remove them.

(From OE-Core rev: 7b781f1532a64973175cffced1eac4cd8bba3d0c)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 4557e95cb39a01ab909cd4dbbe5f0dc4964a306e