mdadm: Fix build on gcc 4.9
Fix

error: right-hand operand of comma expression has no effect
[-Werror=unused-value]

(From OE-Core rev: 9e1aac485175d29951f7ad23cd7515c8f7580271)

(From OE-Core rev: 58da3355522736b93bb6d164739c795068d2a1e8)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 3a9092e9ca6b81dc4c8f4781787744d182edf03c