gnutls: add readline to DEPENDS and add --with-libreadline-prefix
* without this patch it looks for readline in host's /usr/lib
  a) and fails if readline wasn't built before gnutls, because -I is set
     and cannot find header file, this case is better
     configure:33131: checking for readline
     configure:33156: x86_64-oe-linux-gcc    -m64 --sysroot=/OE/oe-core/tmp-eglibc/sysroots/qemux86-64 -std=gnu99 -o conftest -O2 -pipe -g -feliminate-unused-debug-types -I/OE/oe-core/tmp-eglibc/sysroots/qemux86-64/usr/include -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed conftest.c  /usr/lib/libreadline.so >&5
     conftest.c:240:31: fatal error: readline/readline.h: No such file or directory

  b) and finds usable version there if readline was built and MACHINE is compatible with host
     (like qemux86-64 on amd64 host) and then it's passing -L/usr/lib (without sysroot prefix)
     to every build using libgnutls.la
     configure:33131: checking for readline
     configure:33156: x86_64-oe-linux-gcc    -m64 --sysroot=/OE/shr-core/tmp-eglibc/sysroots/qemux86-64 -std=gnu99 -o conftest -O2 -pipe -g -feliminate-unused-debug-types -I/OE/shr-core/tmp-eglibc/sysroots/qemux86-64/usr/include -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed conftest.c  /usr/lib/libreadline.so >&5
     configure:33156: $? = 0
     configure:33173: result: yes
     configure:33185: checking how to link with libreadline
     configure:33187: result: /usr/lib/libreadline.so
     configure:33199: checking readline/readline.h usability
     configure:33199: x86_64-oe-linux-gcc    -m64 --sysroot=/OE/shr-core/tmp-eglibc/sysroots/qemux86-64 -std=gnu99 -c -O2 -pipe -g -feliminate-unused-debug-types -I/OE/shr-core/tmp-eglibc/sysroots/qemux86-64/usr/include conftest.c >&5
     configure:33199: $? = 0
     configure:33199: result: yes
     configure:33199: checking readline/readline.h presence
     configure:33199: x86_64-oe-linux-gcc -E --sysroot=/OE/shr-core/tmp-eglibc/sysroots/qemux86-64    -m64 -I/OE/shr-core/tmp-eglibc/sysroots/qemux86-64/usr/include conftest.c
     configure:33199: $? = 0
     configure:33199: result: yes
     configure:33199: checking for readline/readline.h
     configure:33199: result: yes

(From OE-Core rev: 044f99155bf8775481b70cbe02745c6d9ae1d6a9)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 8ca00617444ab6a919b099c62f58e6ac9c393a89