git: fix installed-vs-shipped QA Issue
Since commit set default libexecdir to $prefix/libexec
...
commit ec7e35833c0f7fe5b9d1f9dccd027532ad65f91a [formerly f35b2e29d9bfa817e64b83df11ebbbfe0f4e8e5c]
Author: Ross Burton <ross.burton@intel.com>
Date:   Tue Apr 30 20:35:54 2013 +0100

    bitbake: set default libexecdir to $prefix/libexec
...

It casued '${D}${libdir}' does not exist, and the following
move operation incorrect which triggered QA Issue:
...
ERROR: git-2.7.0-r0 do_package: QA Issue: git: Files/directories were installed but not shipped in any package:
  /usr/lib64
  /usr/lib64/site_perl
  /usr/lib64/site_perl/5.22.1
...

(From OE-Core rev: 2b82a475a7c8310f432b872e9d1e5eca262a03ee)

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 26f951b99d075be0be27ad6ecee0a48737c28140