ofono: upgrade to 1.6
* 1.5 is not compatible with glib-2.32 and newer
  | In file included from gisi/client.h:30:0,
  |                  from gisi/client.c:33:
  |/OE/shr-core/tmp-eglibc/sysroots/spitz/usr/include/glib-2.0/glib/gtypes.h:28:2: error: #error "Only <glib.h> can be included directly."

(From OE-Core rev: 72684aac1d97469ee5cf9ef0d017a8b933e2a6d6)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 88bb7ce9e9b3b0fcfc251333f83816cc33ad0906