qemu: exclude some ARM EABI obsolete syscalls
some syscalls are obsolete and no longer available for EABI, exclude them to
fix the below error:
        In file included from qemu-seccomp.c:16:0:
        qemu-seccomp.c:28:7: error: '__NR_select' undeclared here (not in a function)
              { SCMP_SYS(select), 252 },
                ^
        qemu-seccomp.c:36:7: error: '__NR_mmap' undeclared here (not in a function)
              { SCMP_SYS(mmap), 247 },
                ^
        qemu-seccomp.c:57:7: error: '__NR_getrlimit' undeclared here (not in a function)
              { SCMP_SYS(getrlimit), 245 },
                ^
        qemu-seccomp.c:96:7: error: '__NR_time' undeclared here (not in a function)
              { SCMP_SYS(time), 245 },
                ^
        qemu-seccomp.c:185:7: error: '__NR_alarm' undeclared here (not in a function)
              { SCMP_SYS(alarm), 241 },

please refer source files:
        arch/arm/include/uapi/asm/unistd.h
or kernel header:
        /usr/include/asm/unistd.h

(From OE-Core rev: 49257247fdc57e9296520bbd598fd8cbf425d44a)

Signed-off-by: Roy.Li <rongqing.li@windriver.com>
Signed-off-by: Saul Wold <sgw@linux.intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 58e3c4d56be159fe8dedd398527caf625458f380