u-boot-mkimage: fix recompile error
Fixed:
make: *** No rule to make target `/path/to/sysroot/4.9.0/include/stddef.h', needed by `crc32.o'.  Stop.
make: *** Waiting for unfinished jobs....
ERROR: oe_runmake failed

This happens when upgrade gcc from 4.9.0 to 4.9.1, and the .depend isn't
regenerated when recompile, the content of it are:

[snip]
crc32.o: /path/to/sysroot/4.9.0/include/stddef.h
[snip]

And Makefile includes the .depend file if it exists, so there would be
errors when /path/to/sysroot/4.9.0/include/stddef.h doesn't exist.

Remove .*.d (a few .d files, its Makefile uses this wildcard) will fix
the problem.

(From OE-Core rev: b31dd7d1fbdd9165872a31c11c6627549609fcb3)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Saul Wold <sgw@linux.intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 8371105be5af4ba88b6b4c862eb7cad852922cf1