avahi-ui: fix for building systemd with multilib
Fixed:
MACHINE = "qemux86-64"
VIRTUAL-RUNTIME_init_manager = " systemd "
DISTRO_FEATURES_append = " systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED += " sysvinit "

require conf/multilib.conf
MULTILIBS = "multilib:lib32"
DEFAULTTUNE_virtclass-multilib-lib32 = "x86"

$ bitbake avahi avahi-ui
ERROR: QA Issue: avahi-ui: Files/directories were installed but not shipped
  /lib
  /lib/systemd
  /lib/systemd/system
  /lib/systemd/system/avahi-daemon.socket
  /lib/systemd/system/avahi-dnsconfd.service
  /lib/systemd/system/avahi-daemon.service [installed-vs-shipped]
ERROR: The recipe avahi-ui is trying to install files into a sharedarea when those files already exist. Those files and their manifestlocation are:
   /path/to/sysroots/qemux86-64/lib/systemd/system/avahi-daemon.socket
 Matched in manifest-qemux86-64-avahi.populate_sysroot
 /path/to/sysroots/qemux86-64/lib/systemd/system/avahi-dnsconfd.service
 Matched in manifest-qemux86-64-avahi.populate_sysroot
 /path/to/sysroots/qemux86-64/lib/systemd/system/avahi-daemon.service
 Matched in manifest-qemux86-64-avahi.populate_sysroot
Please verify which recipe should provide theabove files.

And remove the duplicated line:
rm ${D}${base_libdir} -rf

(From OE-Core rev: 1e6ec39d4996d2812b01c4452c579e476e70e85d)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: afeb590d935baba22d064387c10b7735fae788d2