guile: don't use the identifier 'noreturn'
Fix the build error of autogen-native which depends on guile-native:

ysroots/x86_64-linux/usr/include/guile/2.0/libguile/error.h:40:24: error: expected ')' before '__attribute__'
sysroots/x86_64-linux/usr/include/guile/2.0/libguile/error.h:40:24: error: expected ',' or ';' before ')' token
sysroots/x86_64-linux/usr/include/guile/2.0/libguile/error.h:42:27: error: expected ')' before '__attribute__'

[YOCTO #5743]

(From OE-Core rev: 05d226bee199e9d45f0bb6143d3a78f3f2e93186)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: ed9dca641707fe8ee109317194308b7aa87f1595