directfb: disable imlib2 explicitly
When HOST machine installed imlib2, compiling directfb in OE will
direct this library, and try to use it. This is wrong, since there is
no imlib in OE, so we should disable it explicitly here.

Error as following:
| idirectfbimageprovider_imlib2.c:64:20: fatal error: Imlib2.h: No such
file or directory

Config.log as following (which is wrong):
configure:19602: checking for imlib2-config
configure:19620: found /usr/bin/imlib2-config
configure:19633: result: /usr/bin/imlib2-config

(From OE-Core rev: fbdee213465f38791f3dd6c2663f2fe295be3596)

Signed-off-by: Dennis Lan <dennis.yxun@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 125e702dc5b0d1b3fbf92c9436f6f0de142ca90a