valgrind: depends on boost when ptest
Fixed:
drd/tests/boost_thread.cpp:5:38: fatal error: boost/thread/condition.hpp: No such file or directory
 #include <boost/thread/condition.hpp>

(From OE-Core rev: 5650ece64f55044a8fd7fa3fce692dfb17006f8f)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 588342f2c07d03377fe7b2f0c3df657ac1119f49