at: fix configure option with/without-selinux
without-selinux doesn't work since WITH_SELINUX is always be defined no
matter which option is given: with-selinux, without-selinux.

This causes build errors if '--without-selinux' is used and libselinux
is not buildable in project:

  atd.c:87:29: fatal error: selinux/selinux.h: No such file or directory

(From OE-Core rev: f1f676cf720b869999553eecdb113a2a2daa61fe)

Signed-off-by: Wenzong Fan <wenzong.fan@windriver.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: c5c9ed67add46e5fcb1a3ccb98b471c6228ced4d