alsa-lib: topology: Add missing include sys/stat.h
Fixes this build error with uclibc:

alsa-lib-1.1.0/src/topology/parser.c: In function 'snd_tplg_build_file':
alsa-lib-1.1.0/src/topology/parser.c:262:35: error: 'S_IRUSR' undeclared
(first use in this function)
open(outfile, O_RDWR | O_CREAT, S_IRUSR | S_IWUSR);

(From OE-Core rev: 9ec2c6d4fd9c5c1f745f4d402922b73649ff6287)

Signed-off-by: Maxin B. John <maxin.john@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 069cdbe4dda422374412bf3fa734156b21e078bf