slang: Fix namespace conflict vis-a-vis posix_close
Fixes errors like

|
/home/ubuntu/work/oe/openembedded-core/build/tmp-musl/work/core2-64-oe-linux-musl/slang/2.2.4-r12/slang-2.2.4/src/slpo
sio.c:366:12: error: conflicting types for 'posix_close'
|  static int posix_close (SLFile_FD_Type *f)
|             ^
| In file included from
/home/ubuntu/work/oe/openembedded-core/build/tmp-musl/work/core2-64-oe-linux-musl/slang/2.2.4-r1
2/slang-2.2.4/src/slinclud.h:20:0,
|                  from
/home/ubuntu/work/oe/openembedded-core/build/tmp-musl/work/core2-64-oe-linux-musl/slang/2.2.4-r1
2/slang-2.2.4/src/slposio.c:24:
|
/home/ubuntu/work/oe/openembedded-core/build/tmp-musl/sysroots/qemux86-64/usr/include/unistd.h:38:5:
note: previous de
claration of 'posix_close' was here
|  int posix_close(int, int);
|      ^
| make[1]: ***
[/home/ubuntu/work/oe/openembedded-core/build/tmp-musl/work/core2-64-oe-linux-musl/slang/2.2.4-r12/slang-
2.2.4/src/elfobjs/slposio.o] Error 1

(From OE-Core rev: 6b0cebe506b73cee7591089b624b69e009100c89)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 27a850ab08043c99681098183173e8f71e3d737d