libepoxy: DEPENDS on virtual/egl and virtual/libx11
Fixed do_configure error:
configure: error: libX11 headers (libx11-dev) required to build with GLX support
and do_compile error:
../include/epoxy/egl_generated.h:10:29: fatal error: EGL/eglplatform.h: No such file or directory
 #include "EGL/eglplatform.h"

The dependencies form its README.md:
* automake
* libegl1-mesa-dev
* xutils-dev

(From OE-Core rev: 04193b96fa6e41f9de7ea5eb15be133ac63b1ecc)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Former-commit-id: 529c4c082246a8c2579033fa7311fe91c08be7b9